<?php

function jester_menu() {
  $items['jest'] = array(
      'title' => 'Jestor!',
      'page callback' => 'jester_main',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
  );
  $items['jest/get_root_quests'] = array(
      'title' => 'Ground Get Root Quests',
      'page callback' => 'jester_get_root_quests',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
  );

  return $items;
}

function jester_init() {
  global $jester;
  
  $path = drupal_get_path('module', 'jester');
  $json = file_get_contents($path . '/json/settings.json');
  if (!$json)
    throw new Exception('Could not find settings.json!');

  $settings = json_decode($json);
  if (!$settings)
    throw new Exception('Invalid JSON in settings.json!');

  $ground = new Ground($settings->database);
  $jester = $ground->add_module('jester');
  $jester->settings = $settings;
  Ground::$vineyard_ground = $ground;
}

function jester_embed_settings() {
  global $jester;
  return json_encode($jester->settings->garden);
}

function jester_main() {
  global $jester;
  $ground = Ground::$vineyard_ground;
  $path = drupal_get_path('module', 'jester');
  drupal_set_html_head('<script type="text/javascript" src="' . $jester->settings->paths->metahub . '"></script>');
  drupal_set_html_head('<script type="text/javascript" src="' . $jester->settings->paths->bloom . '/js/bloom.js"></script>');
  drupal_set_html_head('<script type="text/javascript" src="' . $jester->settings->paths->bloom . '/js/vineyard.js"></script>');
  drupal_set_html_head('<script type="text/javascript" src="' . $jester->settings->paths->bloom . '/js/garden.js"></script>');
  drupal_add_js($path . '/js/jester.js');
  drupal_add_css($path . '/styles/editor.css');

  ob_start();
  include $path . '/templates/main.php';
  $string = ob_get_clean();
  return $string;
}

function jester_set_jquery_path() {
//  drupal_set_message($_GET['q']);
  if (substr($_GET['q'], 0, 5) != 'admin' && $_GET['q'] != 'front') {
//    drupal_set_message('new');
    return array('none' => 'jquery-1.7.1.js', 'min' => 'jquery-1.7.1.min.js');
  }
}

function jester_vineyard($action) {
  $ground = Ground::$vineyard_ground;
  $query = $ground->create_query($_RETRIEVE['trellis']);
}

function jester_get_root_quests() {
  $ground = Ground::$vineyard_ground;
  $query = $ground->create_query('quest');
  $query->add_filter('quests.parent IS NULL');
  $query->add_post('ORDER BY name');

  $result = $query->run_as_service(true);
  drupal_json($result);
}
