<?php

function jesters_quest_menu() {
  $items['jest'] = array(
      'title' => 'Jestor!',
      'page callback' => 'jesters_quest_main',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
  );
  $items['quest'] = array(
      'title' => 'Get Quest',
      'page callback' => 'jesters_quest_get_quest',
      'access callback' => TRUE,
      'page arguments' => array(1),
      'type' => MENU_CALLBACK,
  );

  return $items;
}

function jesters_quest_initialize() {
  global $jester;
  $path = drupal_get_path('module', 'jesters_quest');
  $json = file_get_contents($path . '/json/settings.json');
  if (!$json)
    throw new Exception('Could not find settings.json!');

  $jester = new Jesters_Quest();
  $jester->settings = json_decode($json);
}

function jester_embed_settings() {
  global $jester;
  return json_encode($jester->settings->garden);
}

function jesters_quest_main() {
  global $jester;
  jesters_quest_initialize();
  $path = drupal_get_path('module', 'jesters_quest');
  drupal_set_html_head('<script type="text/javascript" src="' . $jester->settings->paths->metahub . '"></script>');
  drupal_set_html_head('<script type="text/javascript" src="' . $jester->settings->paths->bloom . '"></script>');
  drupal_set_html_head('<script type="text/javascript" src="' . $jester->settings->paths->vineyard . '"></script>');
  drupal_add_js($path . '/js/jester.js');

  ob_start();
  include $path . '/templates/main.php';
  $string = ob_get_clean();
  return $string;
}

function jesters_quest_set_jquery_path() {
//  drupal_set_message($_GET['q']);
  if (substr($_GET['q'], 0, 5) != 'admin' && $_GET['q'] != 'front') {
//    drupal_set_message('new');
    return array('none' => 'jquery-1.7.1.js', 'min' => 'jquery-1.7.1.min.js');
  }
}

function jesters_quest_vineyard($action) {
  global $jester;
  jesters_quest_initialize();
  $ground = new Ground($jester->settings->database);
  
  $query = $ground->create_query($_RETRIEVE['trellis']);
//  return $query->
  
}